import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import ImageReel from "../components/ImageReel/ImageReel";

type HomeProps = {
  title: string;
};

const Home: NextPage<HomeProps> = ({ title }) => {
  return (
    <div>
      <Head>
        <title>{title === "Home" ? "Red Square Agency Clone" : null}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header pageTitle={title == "Home" ? "Work" : "Red Square"} />
      <main>
        <Wrapper>
          <Heading>
            The agency for <br /> what comes next.
          </Heading>

          <ReelSection>
            <ImageReelWrapper>
              <ImageReel />
            </ImageReelWrapper>
          </ReelSection>

          <section>
            <Paragraph>
              We deal in ideas, design and media that are category defying. When
              the world Millis, you&#39;ve got to Vanilli.
            </Paragraph>

            <SecondParagraph>
              Red Square believes in rigorous development of brand strategy and
              whip-smart execution. We make all sorts of things. Things that
              move markets, compel audiences and sell product. We help great
              brands create what comes next.
            </SecondParagraph>
          </section>

          <ClientSection>
            <ListHeading>Select Clients</ListHeading>
            <div>
              <List>
                <li>Cherokee Casinos</li>
                <li>Flipboard</li>
                <li>Foxwoods</li>
                <li>Glanbia Nutritionals</li>
                <li>Google</li>
                <li>Hard Rock</li>
                <li>Hibbett Sports</li>
                <li>Hilton Worldwide</li>
                <li>Jack Daniel&#39;s</li>
              </List>
              <List>
                <li>Nescafé</li>
                <li>New York Pride</li>
                <li>Patreon</li>
                <li>Rivers Casino</li>
                <li>Snickers</li>
                <li>Southern Comfort</li>
                <li>The University of Alabama</li>
                <li>Twix</li>
                <li>Wind Creek Hospitality</li>
              </List>
            </div>
          </ClientSection>
        </Wrapper>
      </main>
      <Footer pageTitle={title == "Home" ? "Work" : "Red Square"} />
    </div>
  );
};

Home.defaultProps = {
  title: "Home",
};

const Wrapper = styled.div`
  padding-inline: var(--mobile-padding-inline);
  color: var(--color-white);
`;

const Heading = styled.h1`
  padding-top: clamp(11rem, 45vw, 12.5rem);
  font-family: var(--font-volkhov);
  font-size: 2.3rem;
  font-weight: 700;
  line-height: 2.8rem;
`;

const ReelSection = styled.div`
  padding-top: clamp(2rem, 9vw, 4rem);
  padding-bottom: 28px;
  margin-inline: calc(var(--mobile-padding-inline) * -1);
  border: 1px solid red;
`;

const ImageReelWrapper = styled.div`
  width: 100%;
  height: clamp(190px, 56vw, 400px);
  border: 2px solid blue;
`;

const Paragraph = styled.p`
  font-family: var(--font-poppins);
  font-size: 1.7rem;
  line-height: 1.5;
  padding-block: 36px;
  font-weight: 600;
`;

const SecondParagraph = styled.p`
  padding-bottom: 36px;
  font-family: var(--font-poppins);
  font-size: 1.3rem;
  font-weight: 500;
  line-height: 1.5;
`;

const ClientSection = styled.section`
  border-top: 1px solid var(--color-gray);
  border-bottom: 1px solid var(--color-gray);
  padding: 36px 0 28px 0;
`;

const ListHeading = styled.div`
  font-family: var(--font-poppins);
  color: var(--color-gray);
  font-size: 1.1rem;
  font-weight: 300;
  padding-bottom: 12px;
`;

const List = styled.ul`
  list-style: none;
  padding-inline: 0;

  li {
    font-family: var(--font-poppins);
    font-size: 1.3rem;
    line-height: 1.7;
  }
`;

export default Home;
