import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import Image from "next/image";
import WorkList from "../components/WorkList/WorkList";
import styled from "styled-components";
import fs from "fs";

type WorkProps = {
  title: string;
  images: string[];
};

const Work: NextPage<WorkProps> = ({ title, images }: WorkProps) => {
  return (
    <div>
      <Head>
        <title>{title === "Work" ? "Work" : null}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header pageTitle={title == "Work" ? "Red Square" : "Work"} />

      <main>
        <WorkList images={images} />
      </main>

      <Footer pageTitle={title == "Work" ? "Red Square" : "Work"} />
    </div>
  );
};

Work.defaultProps = {
  title: "Work",
};

export const getStaticProps: GetStaticProps = async () => {
  const folderpath = "./public/images";
  let images = fs.readdirSync(folderpath);
  return {
    props: {
      images,
    },
  };
};

export default Work;
