import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import Image from "next/image";
import WorkList from "../components/WorkList/WorkList";
import styled from "styled-components";
import fs from "fs";
import NugsModal from "../components/NugsModal/NugsModal";
import { usePageContext } from "../hooks/pageContext";
import Backdrop from "../components/Backdrop/Backdrop";

type WorkProps = {
  title: string;
  images: string[];
  logos: string[];
};

const Work: NextPage<WorkProps> = ({ title, images, logos }: WorkProps) => {
  const context = usePageContext();
  const toggleModal = context.toggleModal;

  return (
    <div>
      <Head>
        <title>{title === "Work" ? "Work" : null}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header pageTitle={title == "Work" ? "Red Square" : "Work"} />

      <Main>
        <WorkList images={images} logos={logos} />
      </Main>

      <Footer pageTitle={title == "Work" ? "Red Square" : "Work"} />

      <NugsModal toggleModal={toggleModal} />

      <Backdrop />
    </div>
  );
};

Work.defaultProps = {
  title: "Work",
};

const Main = styled.div`
  isolation: isolate;
`;

export const getStaticProps: GetStaticProps = async () => {
  const imagesPath = "./public/images";
  const logosPath = "./public/logos";
  let images = fs.readdirSync(imagesPath);
  let logos = fs.readdirSync(logosPath);
  return {
    props: {
      images,
      logos,
    },
  };
};

export default Work;
